
package com.tuscanyscatours.payment.creditcard;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "authorizeFault", targetNamespace = "http://www.tuscanyscatours.com/CreditCardPayment/")
public class AuthorizeFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AuthorizeFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AuthorizeFault_Exception(String message, AuthorizeFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AuthorizeFault_Exception(String message, AuthorizeFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.tuscanyscatours.payment.creditcard.AuthorizeFault
     */
    public AuthorizeFault getFaultInfo() {
        return faultInfo;
    }

}
