
package com.tuscanyscatours.payment.creditcard;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CreditCardPaymentService", targetNamespace = "http://www.tuscanyscatours.com/CreditCardPayment/", wsdlLocation = "file:/Users/Valerio/Documents/workspace/Tuscany/workspace/TravelSample-2/payment-java/src/main/resources/CreditCardPayment.wsdl")
public class CreditCardPaymentService
    extends Service
{

    private final static URL CREDITCARDPAYMENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.tuscanyscatours.payment.creditcard.CreditCardPaymentService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.tuscanyscatours.payment.creditcard.CreditCardPaymentService.class.getResource(".");
            url = new URL(baseUrl, "file:/Users/Valerio/Documents/workspace/Tuscany/workspace/TravelSample-2/payment-java/src/main/resources/CreditCardPayment.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/Users/Valerio/Documents/workspace/Tuscany/workspace/TravelSample-2/payment-java/src/main/resources/CreditCardPayment.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CREDITCARDPAYMENTSERVICE_WSDL_LOCATION = url;
    }

    public CreditCardPaymentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditCardPaymentService() {
        super(CREDITCARDPAYMENTSERVICE_WSDL_LOCATION, new QName("http://www.tuscanyscatours.com/CreditCardPayment/", "CreditCardPaymentService"));
    }

    /**
     * 
     * @return
     *     returns CreditCardPayment
     */
    @WebEndpoint(name = "CreditCardPaymentPort")
    public CreditCardPayment getCreditCardPaymentPort() {
        return super.getPort(new QName("http://www.tuscanyscatours.com/CreditCardPayment/", "CreditCardPaymentPort"), CreditCardPayment.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditCardPayment
     */
    @WebEndpoint(name = "CreditCardPaymentPort")
    public CreditCardPayment getCreditCardPaymentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tuscanyscatours.com/CreditCardPayment/", "CreditCardPaymentPort"), CreditCardPayment.class, features);
    }

}
