
package com.tuscanyscatours.payment.creditcard;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CreditCardPayment", targetNamespace = "http://www.tuscanyscatours.com/CreditCardPayment/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditCardPayment {


    /**
     * 
     * @param amount
     * @param creditCard
     * @return
     *     returns java.lang.String
     * @throws AuthorizeFault_Exception
     */
    @WebMethod(action = "http://www.tuscanyscatours.com/CreditCardPayment/authorize")
    @WebResult(name = "Status", targetNamespace = "")
    @RequestWrapper(localName = "authorize", targetNamespace = "http://www.tuscanyscatours.com/CreditCardPayment/", className = "com.tuscanyscatours.payment.creditcard.Authorize")
    @ResponseWrapper(localName = "authorizeResponse", targetNamespace = "http://www.tuscanyscatours.com/CreditCardPayment/", className = "com.tuscanyscatours.payment.creditcard.AuthorizeResponse")
    public String authorize(
        @WebParam(name = "CreditCard", targetNamespace = "")
        CreditCardDetailsType creditCard,
        @WebParam(name = "Amount", targetNamespace = "")
        float amount)
        throws AuthorizeFault_Exception
    ;

}
