package cn.edu.nju.moon.conup.spi.utils;

public enum DepOperationType {
	
	//tx operations
	ACK_SUBTX_INIT,
	NOTIFY_SUBTX_END,
	NOTIFY_ROOT_TX_END,
	NOTIFY_START_REMOTE_SUB_TX,
	
	/** Quiescence Operation type*/
	/** request a component to passivate itself */
	REQ_PASSIVATE,
	/** ACK passivate */
	ACK_PASSIVATE,

	NOTIFY_FUTURE_CREATE,
	ACK_FUTURE_CREATE,
	NOTIFY_FUTURE_REMOVE,
//	NOTIFY_SUBTX_END,
	NOTIFY_PAST_CREATE,
	NOTIFY_PAST_REMOVE,
	//ondemand event type
	REQ_ONDEMAND_SETUP,
	CONFIRM_ONDEMAND_SETUP,
	NOTIFY_FUTURE_ONDEMAND,
	NOTIFY_PAST_ONDEMAND,
	NOTIFY_SUB_FUTURE_ONDEMAND,
	NOTIFY_SUB_PAST_ONDEMAND,
	ACK_FUTURE_ONDEMAND,
	ACK_PAST_ONDEMAND,
	ACK_SUB_FUTURE_ONDEMAND,
	ACK_SUB_PAST_ONDEMAND,
		
	
	/** notify that a remote update is done */
	NOTIFY_REMOTE_UPDATE_DONE,
}
